version: "3"

services:
  dev:
    links:
      - db
    image: 415148673/golang-web-base-image@sha256:2170bda5828e67cff10c91c5cfdfc38fec3807d518acde2a77eeee549440a0d1
    environment:
      - PORT=8080
      - DB_USER=docker
      - DB_PASSWORD
      - DB_HOST=db
      - DB_NAME=webstarter
    volumes:
      - .:/go/src/golang-web-starter
#      - golang-vender-cache:/go/src/golang-web-starter/vendor
    working_dir: /go/src/golang-web-starter
    ports:
      - "3000:3000"
    command: gin

  db:
    image: 415148673/postgres@sha256:6d4800c53e68576e05d3a61f2b62ed573f40692bcc72a3ebef3b04b3986bb70c
    volumes:
      - go-web-starter-db-cache:/var/lib/postgresql/data

volumes:
#  golang-vender-cache:
  go-web-starter-db-cache: