version: "3"

services:
  dev:
    depends_on:
      - db
    image: 415148673/golang-web-base-image@sha256:5cebcc621de0143ac0ead941dd2eea248d02d92d7830516c1533ae63427a9d8f
    environment:
      - DB_USER=docker
      - DB_PASSWORD
      - DB_HOST=db
      - DB_NAME=webstarter
    volumes:
      - .:/go/src/golang-web-starter
#      - golang-vender-cache:/go/src/golang-web-starter/vendor
    working_dir: /go/src/golang-web-starter
    ports:
      - "8080:8080"
    command: go run main.go

  db:
    image: 415148673/postgres@sha256:6d4800c53e68576e05d3a61f2b62ed573f40692bcc72a3ebef3b04b3986bb70c
    volumes:
      - go-web-starter-db-cache:/var/lib/postgresql/data

volumes:
#  golang-vender-cache:
  go-web-starter-db-cache: